# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push (A push gets triggered also when a Pull Request is merged)
# events but only for the main branch
on:
  push:
    branches: [ main ]
    paths:
    - 'criptografia-book/**'
    - '.github/workflows/**.yml'

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        sudo apt-get install python3-pip
        sudo apt-get install -y pandoc
        pip install sphinx
        pip install furo
        pip install myst-parser
        pip install nbsphinx
        pip install sphinx-copybutton
        pip install ipython
        pip install sphinx-thebe
        PATH="${PATH}:${HOME}/.local/bin"

    # Build the site
    - name: Build the site
      run: |
        sphinx-build criptografia-book criptografia-book/_build

    # Push the site's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./criptografia-book/_build/
